# Generated by Django 5.0.4 on 2024-06-08 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='file_resume',
            field=models.FileField(upload_to='file-resume/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_project',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
