# Generated by Django 5.0.4 on 2024-06-09 21:29

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0006_aboutme_profile_photo_alter_portfolio_image_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_project',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 667], upload_to='images/'),
        ),
    ]
