# Generated by Django 5.0.4 on 2024-06-11 07:09

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0007_alter_portfolio_image_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='profile_photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='profile_photos'),
        ),
    ]
