# Generated by Django 5.0.4 on 2024-06-12 12:54

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0008_alter_aboutme_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('all_projects', 'All Projects'), ('python', 'Python'), ('django', 'Django'), ('php', 'PHP')], default='all_projects', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='profile_photos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
