# Generated by Django 5.0.4 on 2024-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0009_portfolio_category_alter_aboutme_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('php', 'PHP')], default='all_projects', max_length=50),
        ),
    ]
