# Generated by Django 5.0.4 on 2024-07-31 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0012_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('skype', 'Skype')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('about_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
