# Generated by Django 5.0.4 on 2024-07-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0013_socialmedias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedias',
            old_name='about_me',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='socialmedias',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('skype', 'Skype'), ('github', 'GitHub')], max_length=50),
        ),
    ]
